### ISSUE TITLE
Save work to continue later

### ISSUE THREAD

**Issue by sergeichab** [grishkam/QuickFigures#1]
Hi Gregory,

I am giving a try to QuickFigures. So far it looks useful, thank you for creating it!

I wonder whether I am being blind or it is not implemented… Is it possible to save a work and continue working on it later with QuickFigures? It is not possible with the svg file (not surprising i guess).

Thank you!

Sergei

**Comment by grishkam** [comment]
Hello Sergei,
It is indeed possible to save work and continue later. 
Those options are under the QuickFigures' File menu.
Assuming that you downloaded QuickFigures recently, the options you need should be 
File->Save->Current Worksheet
File->Open->Saved Worksheet
These allow you to save work and continue later. However, I would only use this for short term storage of work. 
Later updates to QuickFigures will not be able to open files saved with older forms of the package (and vice versa). 
Let me know if you encounter any other issues or bugs.

**Comment by sergeichab** [comment]
I totally missed it... I was only looking at "Export", sorry!

And thank you very much!

Good to know that they would not be compatible with future updates.

Sergei
