### ISSUE TITLE
Unable to Add Multiple Figures with Only Merge in One Canvas

### ISSUE THREAD

**Issue by nbstutzman** [grishkam/QuickFigures#11]
Hi,

I am trying to add Merge-Only Figures to a canvas, and am having trouble. Getting the first Merge-Only Figure in a canvas isn't hard; I can create a canvas with one via File>New>Figure with Merge Panels Only. The problem is getting a second Merge-Only Figure to be in the same canvas. 

If I do the same as above, it automatically opens a _new_ canvas with the Merge-Only Figure. Another way I have tried is to add a Split-Channel Figure (via Quick Multichannel Figure or dragging in a file) and then delete the extraneous channels. However, when I try to do this, I keep get an error. Weirdly, I am able to sometimes delete one or two channels within an figure, but there is always one channel that I cannot delete without getting an impassible error.

A third method I have thought of is to add all my images to the first Merge-Only Figure, and then somehow split it into multiple figures, but I cannot find a way to split one figure into two.

Let me know what other information I can provide to help resolve this issue, or if there is a simple fix I am missing.

I am new to QuickFigures and really excited about it!

Thanks,
Nathan

**Comment by grishkam** [comment]
Hi Nathan,
If you right click on an image panel and go the the "Figure" submenu, there
will be an option called "Recreate All Panels".
A dialog box with many options will appear. Under the "Created Panels"
option, you can select Merge Panel Only and OK the dialog.

Have a great day,
Greg

**Comment by grishkam** [comment]
Also, I found a fix for the error you mentioned and will update
QuickFigures later this week.

Thanks for reporting this,
Greg

**Comment by grishkam** [comment]
I fixed the error message you mentioned. If you updated QuickFigures in the past couple days, the new version should work. In the future, I will add an options to use drag-drop to create merge-only figures directly.
