### ISSUE TITLE
Selecting "Don't Merge These Channel(s)"

### ISSUE THREAD

**Issue by jwrth** [grishkam/QuickFigures#2]
Hi @grishkam,

Firstly, thanks a lot for this amazing tool! It helps a lot with the daily work in ImageJ!

I have one question: When I have a multichannel image and want to exclude one channel from the Merge tile this doesn't work for me. I can open the dropdown menu but I can't select one of the options. When I click on one of them nothing happens. Here a screenshot of the situation:

![image](https://user-images.githubusercontent.com/76480183/156128618-aa2a4ba3-3435-4df6-a1f4-5a08d6f7121a.png)

After selecting one channel it just sticks with "none selected". However, the option "Go up to channel" works perfectly. But for example in the case above I'd like to exclude the brightfield channel which comes second.

Do you have an idea what's the problem? Is it a bug or do I just have to do anything differently?

Thanks a lot in advance!

**Comment by grishkam** [comment]
Thank you for noticing this bug. I have already determined the source of the issue and fixed the bug. If you update QuickFigures now, it should work perfectly.

**Comment by jwrth** [comment]
Thanks a lot, it's working!!
