### ISSUE TITLE
Please help :( inserts disaster 

### ISSUE THREAD

**Issue by Bind000** [grishkam/QuickFigures#8]
Please help, Quick Figures is unworkable after update, constantly crashes when trying to make inserts.
I attached a list of errors from imagej console.
[Console.txt](https://github.com/grishkam/QuickFigures/files/10833916/Console.txt)

**Comment by grishkam** [comment]
Thank you for letting me know about this problem.
However, it does not occur when I try to make figures with my own images on my own computer. Perhaps there is a specific issue with the type of images you are using? Please send me some example image files.

**Comment by Bind000** [comment]
Hi, 
thank you for the answer, im using .czi files from zeiss confocal . 
I can not upload files cus it is not supported for github:( i can later send on mail 
the problem occurs every time I try to make inserts other than the first image inserted into the figure grid.

**Comment by grishkam** [comment]
Thanks for details. I just tried with my own .czi files and had no problem. 

1. Which version of ImageJ are you using? Go to "Help<About ImageJ..." to find out.
2. You updated QuickFigures, right?
3. You can try one of my Czi files (https://github.com/grishkam/QuickFigures/tree/master/TestingQuickFigures/Testing/Test%20Scale%20Bars)
4. Can you duplicate your own .czi image, and save as tiff?

**Comment by grishkam** [comment]
There error message from the Console.txt suggests that there might be something wrong with your image file and therefore ImageJ thinks there is no image to crop.

**Comment by Bind000** [comment]
Yes, you may be right about that, but the file is exactly the same as always, I have this problem the first time. I check on my desktop and my laptop, and the same error. 
fiji version is 1,53t on my Laptop and now I can check on my desktop but on my desktop, i try a fresh download today so is the newest one. 
Here is the link to google drive with two files (czi)
https://drive.google.com/drive/folders/1hxNTw07xRWHkmGzCk-3rCmSpoffX0Y33?usp=share_link

**Comment by Bind000** [comment]
I tested your file and is perfectly fine, you are 1000% right in the files :( so I think you can close the thread I need to figure out what happened with the files.

**Comment by grishkam** [comment]
I tried making a figure with your images (ImageJ 1.54b) and QuickFigures (current version). There was no problem.

**Comment by Bind000** [comment]
Ok, I think I found the solution/problem. How are you adding new images to the figure? cus in my case problem seems to appear always when I chose to add an image using the method on the picture attached 
![solution](https://user-images.githubusercontent.com/126400660/221428219-3f229469-18bc-499b-84b2-d2eaf1f30c36.jpg)

**Comment by grishkam** [comment]
I have been using drag/drop (dropping images files onto the figure). The method shown above is also working now but might have had a a problem between two recent QuickFigures updates. Try updating QuickFigures again using "Help<update" menu item in ImageJ/Fiji.

**Comment by Bind000** [comment]
ok, thank you for your help.

**Comment by grishkam** [comment]
Thanks for using QuickFigures and keeping me informed about potential problems. Let me know if you have any other issues or have an idea for a new feature.
